#
# Blog Settings
#
author: Lee Madajczyk
description: Lee Madajczyk
url: http://www.madajczyk.com
title: Lee Madajczyk
subtitle: 
gravatar_url: https://en.gravatar.com/userimage/55098/4af4f27ed744084970522c5cb73f19c4.jpg?size=160
# Github repositories
github_user: madajczyk
github_repo_url: https://github.com/madajczyk/madajczyk.com/

# Twitter
twitter_user: lmadajczyk
twitter_tweet_button: true

# LinkedIn
linkedin_user: madajczyk

# Google Plus
google_user: LeeMadajczyk

# Google Analytics
google_analytics_tracking_id: UA-138037-5


#
# Jekyll Settings
#
markdown: rdiscount
pygments: true
permalink: /archive/:year/:month/:day/:title/
rdiscount:
  extensions: [smart]
paginate: 5
paginate_path: "page/:num"
category_dir: categories