#
# Blog Settings
#
author: Lee Madajczyk
description: Lee Madajczyk
url: https://www.madajczyk.com
title: Lee Madajczyk
subtitle:
# Github repositories
github_user: madajczyk
github_repo_url: https://github.com/madajczyk/madajczyk.com/
lang: en

# Twitter
twitter_user: lmadajczyk
twitter_tweet_button: true

# LinkedIn
linkedin_user: madajczyk

# Google Pluss
google_user: LeeMadajczyk

# Google Analytics
google_analytics_tracking_id: UA-138037-5

#RSS
subscribe_rss: https://www.madajczyk.com/atom.xml

#
# Jekyll Settings
#
markdown: kramdown
highlighter: rouge
permalink: /archive/:year/:month/:day/:title/
rdiscount:
  extensions: [smart]
paginate: 5
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
