#
# Blog Settings
#
author: Lee Madajczyk
description: Lee Madajczyk
url: https://madajczyk.com
title: Lee Madajczyk
subtitle:
defaultshowcaseimage: /icons/favicon-196x196.png

# Github repositories
github_user: madajczyk
github_repo_url: https://github.com/madajczyk/madajczyk.com/
lang: en

# Twitter
twitter_user: lmadajczyk
twitter_tweet_button: true

# LinkedIn
linkedin_user: madajczyk

#
# Jekyll Settings
#
markdown: kramdown
highlighter: rouge
permalink: /archive/:year/:month/:day/:title/
rdiscount:
  extensions: [smart]
paginate: 5
paginate_path: "page/:num"
category_dir: categories

feed:
  path: atom.xml

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

algolia:
  application_id: WKO5G7WGJH
  index_name: madajczyk.com
  search_only_api_key: a8844ad6848fe599bac0fea247e39d50