baseURL: https://madajczyk.com
disablePathToLower: true
languageCode: en-us
title: Lee Madajczyk
theme: site
disablePathToLower: false

permalinks:
  archive: /archive/:year/:month/:day/:slug

params:
  author: Lee Madajczyk
  logo: images
  github: madajczyk
  linkedin: madajczyk
  twitter: lmadajczyk
  algolia:
    appId: WKO5G7WGJH
    apiKey: a8844ad6848fe599bac0fea247e39d50
    indexName: madajczyk.com

outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true

outputs:
  home:
    - "html"
    - "rss"
    - "jsonfeed"
  page:
    - "html"
