# netlify.toml
#
# https://docs.netlify.com/integrations/frameworks/hugo/
#

[build]
  command = "hugo"
  publish = "public"
[build.environment]
  HUGO_VERSION = "0.101.0"
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' data: cdnjs.cloudflare.com cdn.jsdelivr.net https://*.algolia.net https://*.algolianet.com 'unsafe-inline';"
